### ISSUE TITLE
Package not found: resolving package Tsdl in /

### ISSUE THREAD

**Issue by lapwat** [Schmavery/FlappyBird#1]
Hi,

First of all, I launched your flappy bird app on my Mac, Qemu & Web versions work well.
Now I try to [dockerize](https://github.com/lapwat/FlappyBird) this app.

The image build works but have this error when running `npm run build:web` :
```
/app # npm run build:web
npm info it worked if it ends with ok
npm info using npm@4.6.1
npm info using node@v8.7.0
npm info lifecycle FlappyBird@0.0.0~prebuild:web: FlappyBird@0.0.0
npm info lifecycle FlappyBird@0.0.0~build:web: FlappyBird@0.0.0

> FlappyBird@0.0.0 build:web /app
> bsb -make-world -backend js

Warning: refmt version missing. It is recommended to set it explicitly, since we may change the default in the future.
ninja: no work to do.
Warning: refmt version missing. It is recommended to set it explicitly, since we may change the default in the future.
ninja: no work to do.
Package not found: resolving package Tsdl in /
File "bsconfig.json", line 1
Error: package Tsdl not found or built , if it is not built
Please run 'bsb -make-world', otherwise please install it
```

Do you know where it can come from ?

Thank you,
lapwat

**Comment by bsansouci** [comment]
Did you run `npm install` before running `npm run build:web`? 
Also make sure you don't use npm5. Use npm4 or yarn.

**Comment by lapwat** [comment]
Yes of course, see the [Dockerfile](https://github.com/lapwat/FlappyBird/blob/master/Dockerfile)

Regards

**Comment by Schmavery** [comment]
I find this pretty mysterious. Can you show the contents of your node_modules (and maybe also the contents of `node_modules/tsdl`?)
Edit: after talking to @bsansouci we think it's a case-sensitivity issue.  Will take another look at reproing using docker.

**Comment by Schmavery** [comment]
Hey @lapwat, thanks so much for reporting this. It had to do with some case-insensitivities between the bs-dependencies and the names of the packages in the package.jsons.  I built the docker image on my machine and it should be working now!
Let me know if it's working for you now or whether you need anything else 😄

**Comment by lapwat** [comment]
It now works like a charm, thank you!
https://flappybird.lapw.at/
It does not work on phone, can you bind screen touch ?

**Comment by Schmavery** [comment]
Great!
Thanks for the suggestion, opened https://github.com/Schmavery/FlappyBird/issues/2 to track it.
